/* ============================================================
   PROJECT: Topology-Optimized Subwoofer
   ------------------------------------------------------------
   This page describes the design without quoting specific
   numbers. If you want to add measured values later (driver
   size, internal volume, impedance, wall thickness, dimensions),
   drop them into the relevant sentence or add a spec row.

   More photos: drop files in this folder and uncomment the
   "figures" blocks below. Worth adding if you have them:
   the SolidWorks design space, the topology optimization result,
   the salvaged drivers before the rebuild, and the internal wiring.
   ============================================================ */
window.Portfolio = window.Portfolio || {};
window.Portfolio["topology-optimized-subwoofer"] = {

  title:   "Topology-Optimized Subwoofer",
  kicker:  "Component-Driven Mechanical Design",
  featured: false,

  blurb:   "A subwoofer built around salvaged drivers from a dead Bose system, with the enclosure generated by SolidWorks topology optimization and every interface driven by hardware I could not change.",
  tagline: "The components came first. The structure was designed to fit them, not the other way around.",

  cover:   "subwoofer.jpg",
  hero:    "subwoofer.jpg",

  tags:    ["Topology Optimization", "Mechanical Design", "SolidWorks", "Electronics Integration"],

  spec: [
    ["Type",    "Custom subwoofer enclosure"],
    ["Role",    "Design, wiring, and integration"],
    ["Drivers", "Salvaged Bose, rewired to a standard impedance"],
    ["Method",  "SolidWorks topology optimization"],
    ["Status",  "Complete"]
  ],

  links: [
    { label: "GitHub", href: "" }
  ],

  sections: [
    {
      id: "overview",
      heading: "Overview",
      body: [
        "A Bose speaker system in my house died. The electronics were finished, but the drivers were still good, so the project became a question of what could be built around hardware I had no ability to change.",
        "That inverts the usual design problem. Normally components are selected to serve a design. Here the components were fixed first, and every dimension of the enclosure had to be derived from them. I did the mechanical design, the wiring, and the sourcing of the amplification."
      ]
    },

    {
      id: "components",
      heading: "The Components Set the Requirements",
      body: [
        "Before any geometry existed, I measured the salvaged drivers and wrote down what each physical property forced the enclosure to do. The list below is the actual requirement set the design was built from."
      ],
      table: {
        head: ["Fixed component property", "Constraint it imposed", "Design response"],
        rows: [
          ["Driver frame bolt pattern", "Mounting holes could not be moved or resized", "Baffle bosses located directly from the measured driver, not from a convenient grid"],
          ["Cone and surround diameter", "Baffle opening fixed by the driver, not chosen", "Opening cut to the driver dimension with clearance for excursion"],
          ["Magnet and basket depth", "Minimum clear depth required behind each baffle", "Internal structure routed around the motor assembly"],
          ["Driver displacement volume", "Reduced the usable air volume inside the box", "Internal volume sized after subtracting the space the drivers themselves occupy"],
          ["Proprietary Bose impedance", "Drivers did not present a standard amplifier load", "Two drivers wired in series to raise the total to a standard impedance"],
          ["Terminal location on the driver", "Leads had to exit without contacting the motor", "Wire routing designed into the internal ribs rather than added afterward"]
        ]
      }
      // figures: [ { src: "drivers-before.jpg", caption: "The salvaged drivers before the rebuild." } ]
    },

    {
      id: "topology",
      heading: "Topology Optimization",
      body: [
        "With the interfaces fixed, the only real design freedom left was where material belonged. Rather than guess at a panel thickness and add ribs by eye, I set the enclosure up as a topology optimization study in SolidWorks.",
        "The design space was the outer envelope minus the volume the drivers and wiring needed. The driver mounting interfaces, the panel seams, and the terminal area were locked as retained regions, since those are the places the structure has to exist regardless of what the optimizer would prefer.",
        "The load case is the one that matters for a speaker cabinet. A driver pushes against its own basket, so the enclosure sees a reaction force along the axis of cone motion, reversing at the drive frequency. Optimizing for stiffness under that load puts material where it resists panel flex and removes it where it was only adding mass.",
        "The result is visible on the finished part. Material is retained in continuous paths between the driver mounts and the corners of the box, and cleared from the middle of the faces, which is what produces the filleted corner webs on the front."
      ]
      // figures: [
      //   { src: "design-space.jpg",  caption: "Design space with the retained regions locked." },
      //   { src: "topology-result.jpg", caption: "Optimization result before it was rebuilt as solid geometry." }
      // ]
    },

    {
      id: "enclosure",
      heading: "Enclosure Design",
      body: [
        "A topology result is a starting point, not a part. The raw output was rebuilt into clean, manufacturable geometry with real wall thicknesses, sealing faces, and fastener provisions.",
        "The acoustic requirements were kept separate from the structural ones and had to hold at the same time. The enclosure had to seal, and it had to keep its own panel resonances away from the band the drivers work in. Stiffening the panels serves both goals at once, since a panel that does not flex also does not radiate sound of its own."
      ],
      list: [
        "Wall sections carried through from the optimization result rather than set to one uniform thickness.",
        "Sealing faces added at every joint so the enclosure holds pressure.",
        "Both drivers stacked on a single baffle to keep the footprint narrow.",
        "Fastener provisions placed so the drivers can be removed without disturbing the structure."
      ]
    },

    {
      id: "electronics",
      heading: "Electronics and Wiring",
      body: [
        "The salvaged drivers came with no usable electronics, so the entire signal chain had to be specified and assembled from scratch. The harder problem was that Bose does not use a standard driver impedance, which is a large part of why these drivers cannot simply be connected to a generic amplifier when the original electronics fail.",
        "Rewiring solved it. Putting the two drivers in series adds their impedances, which brings the proprietary Bose value up to a standard load that an off-the-shelf amplifier can drive safely. Parallel would have done the opposite, dividing the impedance and moving further from standard while presenting a harder load to the amplifier. That single wiring decision is what made commodity amplification possible.",
        "The chain runs from a USB source into an Audioengine D1 digital to analog converter, then into a Pyle amplifier driving the enclosure. I did all of the internal wiring and the terminations."
      ],
      list: [
        "Drivers wired in series, raising the proprietary Bose impedance to a standard amplifier load.",
        "Series chosen over parallel deliberately, since parallel would have halved the impedance instead of raising it.",
        "Amplification sourced to match the resulting load rather than bought first and matched afterward.",
        "Internal leads routed through the structure, away from the motor assemblies.",
        "Terminations and strain relief done so the drivers can be removed without cutting wire."
      ]
      // figures: [ { src: "wiring.jpg", caption: "Internal wiring and terminations." } ]
    },

    {
      id: "result",
      heading: "Result",
      body: [
        "The system is built and in daily use. A set of drivers that would have been thrown out with the dead electronics is now working again inside a structure designed specifically for them.",
        "The part of this project worth keeping is the method rather than the speaker. Starting from components I could not change forced every dimension to trace back to a measured constraint, and using topology optimization meant the material distribution was decided by the load path instead of by habit."
      ]
      // figures: [ { src: "finished.jpg", caption: "The finished enclosure in use." } ]
    }
  ]
};
