name: Build Resume PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: Kestin-Kuhn-Resume.tex
          latexmk_use_lualatex: true

      - uses: actions/upload-artifact@v4
        with:
          name: Kestin-Kuhn-Resume
          path: Resume.pdf
